# Training environment

First, let's ensure access to the GeoServer training environment.
If you are following these materials while participating on the Advanced GeoServer course, you are provided your own GS instance hosted on Amazon Web Services (AWS).
The URL of this instance is provided to you by your course instructor.
You can log in to your GS instance as an administrator with the following credentials:

```
username: admin
password: gispotraining
```

Alternatively, you can also install GeoServer on your local machine.
An easy way to do this is to use Docker, we recommend using the latest version of the [kartoza/geoserver](https://hub.docker.com/r/kartoza/geoserver) image.
Start a new container with the command:

```
docker run --name geoserver\
-e SAMPLE_DATA=true\
-e GEOSERVER_ADMIN_PASSWORD=gispotraining\
--rm kartoza/geoserver:latest
```

After startup, GS is accessible at [http://localhost:8080/](http://localhost:8080/) and you can log in with the credentials above.

If you don't have Docker available, another option is to install and set up Apache Tomcat 9 and OpenJDK 11.
Download the Web Archive (.war) of the latest GS version on [geoserver.org](https://geoserver.org) and place it in the Tomcat webapps directory.
Restart Tomcat, after which GeoServer should be accessible.

## Useful tools

Parts of this course will cover optimising raster and vector spatial data.
For these parts, it is useful to have some tools locally available.

TODO: which tools

It's also highly useful to have a desktop GIS such as QGIS installed.
You can use QGIS as a WMS/WFS client to see how the different services provided by GS work.
